describe("Testing firebase", function(){
    it('Test changing password', function() {
        cy.visit("http://0.0.0.0:3000/signin")
        cy.get("#email").type("testaccount@gmail.com")
        cy.get("#password").type("111111")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.visit("http://0.0.0.0:3000/account")
        cy.get("[type='password']").type("000000")
        cy.get("#change_password").click()
        cy.wait(10000)
        cy.get("#signOut").click()
        cy.wait(10000)
        cy.get("#email").type("testaccount@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.get("#homeHeading").invoke("text").should("eq", "My Home")
    })
})