describe("Testing firebase", function(){
    it("Testing the number of family user owned ", function(){
        cy.visit("https://zerobug.netlify.com/signin")
        cy.get("#email").type("chencl0214@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.get("#artifactItems").children().first().children().first().children().first().children().should('have.length', 6)
        cy.get("#signOut").click()
    })

    it("Testing the number of the artifact user owned", function(){
        cy.visit("https://zerobug.netlify.com/signin")
        cy.get("#email").type("chencl0214@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.get(".container").children().should('have.length', 4)
        cy.get("#signOut").click()
    })

    it("Testing the search bar with one result", function(){
        cy.visit("https://zerobug.netlify.com/signin")
        cy.get("#email").type("chencl0214@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.get("[type='search']").type("testArtifact")
        cy.wait(10000)
        cy.get(".container").children().should('have.length', 2)
        cy.wait(10000)
        cy.get("#signOut").click()
    })

    it("Testing the search bar with two results", function(){
        cy.visit("https://zerobug.netlify.com/signin")
        cy.get("#email").type("chencl0214@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.get("[type='search']").type("test")
        cy.wait(10000)
        cy.get(".container").children().should('have.length', 3)
        cy.wait(10000)
        cy.get("#signOut").click()
    })

    it("Testing the search bar with no result", function(){
        cy.visit("https://zerobug.netlify.com/signin")
        cy.get("#email").type("chencl0214@gmail.com")
        cy.get("#password").type("000000")
        cy.get("[type='submit']").click()
        cy.wait(10000)
        cy.get("[type='search']").type("testing3")
        cy.wait(10000)
        cy.get(".container").children().should('have.length', 1)
        cy.wait(10000)
        cy.get("#signOut").click()
    })
})